server:
  port: 8082
  servlet:
    session:
#     单位/秒
      timeout: 60

spring:
  main:
    allow-bean-definition-overriding: true
    # 时间戳统一转换
  #    jackson:
  #      date-format: yyyy-MM-dd HH:mm:ss
  #      time-zone: GMT+8
  security:
    user:
      name: user
      password: 123

  redis:
    timeout: 6000
    password:
    lettuce:
      pool:
        # 最大活跃链接数 默认8（使用负值表示没有限制）
        max-active: 256
        # 最大空闲连接数 默认8
        max-idle: 16
          # 最小空闲连接数 默认0
        min-idle: 4
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 6000
    cluster:
      nodes:
#        - 192.168.179.4:6379
#        - 192.168.179.4:6380
#        - 192.168.179.4:6381
#        - 192.168.179.4:6382
#        - 192.168.179.4:6383
#        - 192.168.179.4:6384
        - 192.168.137.4:6379
        - 192.168.137.4:6380
        - 192.168.137.4:6381
        - 192.168.137.4:6382
        - 192.168.137.4:6383
        - 192.168.137.4:6384
        # 获取失败 最大重定向次数
      max-redirects: 3

  #  注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

ribbon:
  ConnectTimeout: 5000 # 连接超时时间(ms)
  ReadTimeout: 5000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: lsy-hardware-web #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer'  #JWT负载中拿到开头


