server:
  port: 8081

spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lsy_hardware?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root

  #  注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  main:
    allow-bean-definition-overriding: true

  redis:
    timeout: 6000
    password:
    lettuce:
      pool:
        # 最大活跃链接数 默认8（使用负值表示没有限制）
        max-active: 256
        # 最大空闲连接数 默认8
        max-idle: 16
        # 最小空闲连接数 默认0
        min-idle: 4
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 6000
    cluster:
      nodes:
          - 192.168.179.4:6379
          - 192.168.179.4:6380
          - 192.168.179.4:6381
          - 192.168.179.4:6382
          - 192.168.179.4:6383
          - 192.168.179.4:6384
        #        - 192.168.137.4:6379
        #        - 192.168.137.4:6380
        #        - 192.168.137.4:6381
        #        - 192.168.137.4:6382
        #        - 192.168.137.4:6383
        #        - 192.168.137.4:6384
        # 获取失败 最大重定向次数
      max-redirects: 3

#对于rabbitMQ的支持
  rabbitmq:
    addresses: 192.168.179.4:5672
    username: admin
    password: admin
    virtualHost: /
    publisher-returns: true
    publisher-confirm-type: correlated
    listener:
      simple:
        retry:
          # 开启消费者(程序出现异常)重试机制，默认开启并一直重试
          enabled: true
           # 最大重试次数
          max-attempts: 5
          # 重试间隔时间(毫秒)
          initial-interval: 3000
          # 开启手动ack
        acknowledge-mode: manual

#database type
#设置数据库类型（12种，可选值：oracle, mysql, mariadb, sqlite, hsqldb, postgresql, db2, sqlserver, informix, h2, sqlserver2012, derby）
pagehelper:
  helperDialect: mysql

# 测试属性
useLocalCache: false

elasticsearch:
  ip-port: localhost:9200